### ISSUE TITLE
WSDL bank message altering. 

### ISSUE THREAD

**Issue by dbdness** [dbdness/SI-LoanBroker-Group14#9]
@AlexanderFalk  jeg har et par ønsker til WSDL adapterens response besked, så den er nemmere at trække værdier fra:
1. Interest rate value som camelcase ~ "interestRate".
2. Samt pakke LoanResponse ind i opening/closing værdier. Lidt ala:
<LoanResponse>
<name>BankWSDL</name>
<interestRate>3.948988081599437</interestRate>
<refund>26318.0</refund>
</bank>
</LoanResponse> 

Det ville være super perfekt, for så skulle XMLen være super ligetil at parse!

**Comment by Nordalf** [comment]
Dette er lavet i den nye version af Bank WSDL'en. Se WSDL'en : 
https://github.com/AlexanderFalk/bankadapterXML
